#ifndef COMMANDER_CONFIG_H
#define COMMANDER_CONFIG_H

#include <QtCore/qglobal.h>

#define COMMANDER_VERSION_MAJOR 1
#define COMMANDER_VERSION_MINOR 0
#define COMMANDER_VERSION_PATCH 0
#define COMMANDER_VERSION       COMMANDER_VERSION_CHECK(COMMANDER_VERSION_MAJOR, COMMANDER_VERSION_MINOR, COMMANDER_VERSION_PATCH)

#define COMMANDER_VERSION_STR   "1.0.0"
#define COMMANDER_VERSION_CHECK(major, minor, patch) QT_VERSION_CHECK(major, minor, patch)

#ifdef QT_DEBUG
#   define COMMANDER_DEBUG
#   define COMMANDER_INFO
#   define COMMANDER_WARNING
#   define COMMANDER_CRITICAL
#   define COMMANDER_FATAL
#endif

#endif // COMMANDER_CONFIG_H
